name: mac_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  flutter_read_more_text: ^0.0.1
  carousel_slider: ^1.3.0
  url_launcher: ^5.4.1
  animated_text_kit: ^2.0.0
  firebase_core: ^0.4.4
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.3
  modal_progress_hud: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - images/


